project:
  type: website
  output-dir: docs

website:
  page-footer: 
      border: false
      left: "Copyright 2025, Elmera Azadpour" 
      right: 
        - icon: github
          href: https://github.com/elmeraa-usgs
        - icon: twitter 
          href: https://twitter.com/EAzadpour
  title: "Elmera Azadpour"
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Research
        href: Research.qmd
      - text: Resources
        href: Resources.qmd
      - text: R
        href: R_Resources.qmd
      - text: 2023 Chart Challenge
        href: CC2023.qmd        
      - text: Blog
        href: blog.qmd
      - text: Social Media 
        href: social_media.qmd      
      - icon: github
        href: https://github.com/elmeraa-usgs
      - icon: twitter
        href: https://twitter.com/EAzadpour
  cookie-consent:
    type: implied
    style: headline
    palette: light
  google-analytics:
    tracking-id: "G-4F5QL70Z38"
    anonymize-ip: true
        
format:
  html:
    theme:
      light: [cosmo, ember.scss]
      dark: [darkly, ember.scss]
editor: visual

